# Generated by Django 4.1 on 2022-08-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address_delivery',
            field=models.ManyToManyField(to='Delivery.address', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='file',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Delivery.type', verbose_name='Тип товара'),
        ),
    ]
