# Generated by Django 4.1 on 2022-08-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_alter_address_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address_delivery',
            field=models.ManyToManyField(blank=True, to='Delivery.address', verbose_name='Адрес доставки'),
        ),
    ]
