# Generated by Django 4.1 on 2022-09-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_alter_delivery_address_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='item_name',
            field=models.TextField(blank=True, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Delivery.type', verbose_name='Тип товара'),
        ),
    ]
