# Generated by Django 4.1 on 2022-09-11 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0004_alter_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address_delivery',
            field=models.ManyToManyField(to='Delivery.address', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='item_name',
            field=models.TextField(verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Delivery.type', verbose_name='Тип товара'),
        ),
    ]
